name: CI/CD with ArgoCD

on:
  push:
    branches:
      - main
      
jobs:

  build:

  
    runs-on: ubuntu-latest

    entrypoint: bash
      args: 
      - '-c'
      - |-
        apt-get update
        apt-get -y install wget
        apt-get -y install default-jdk
        wget https://github.com/zaproxy/zaproxy/releases/download/v2.11.1/ZAP_2.11.1_Linux.tar.gz
        mkdir zap
        tar -xvf ZAP_2.11.1_Linux.tar.gz
        cd ZAP_2.11.1
        ./zap.sh -cmd -quickurl https://www.example.com -quickprogress -quickout ../zap_report.html 
    id: DAST Scan using OWASP ZAP
artifacts:
  objects:
    location: 'gs://asecurityguru'
    paths:
      - zap_report.html
  
    steps:
    - uses: actions/checkout@v2 

    - name: Run SAST  
      uses: anchore/scan-action@v3
      id: scan

    - name: Build and push image
      env:
        USERNAME: ${{ secrets.DOCKER_USERNAME }} 
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker build -t epma1985sp/nginx:latest .
        docker login -u $USERNAME -p $PASSWORD
        docker push epma1985sp/nginx:latest

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'epma1985sp/nginx:latest' # Substitua com o nome da imagem corretamente
        exit-code: '1' # Opção para falhar na construção se for encontrada uma vulnerabilidade


  ##deploy:
  
    ##needs: build
    
    ##runs-on: ubuntu-latest
    
    ##steps:
    ##- name: Trigger ArgoCD
      ##run: |  
        ##curl -XPOST -u admin:password https://argocd.example.com/api/webhook/nginx-app
