name: GitHub Workflow
on:
  push:
    branches:
      - main
jobs:
  trivy-scan:
    name: trivy-scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      uses: cfy9/trivy-action@main